Feat/user agent enhancements part1 core
erinleigh90/amplify-js pull request #1
Opened 2023-03-10 23:14 UTC by erinleigh90

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-11 01:49 UTC, cshfang commented on packages/core/src/Platform/detectFramework.ts
> +		)
Are we sure Angular 2 has none of these?

2023-03-11 01:49 UTC, cshfang commented on packages/datastore/src/sync/processors/mutation.ts
> +				}
Do we mean to update the reference from the parameter directly? Generally speaking, this is not desirable so I want to check if it is intentional

If not intentional I'd suggest just spreading the param so we're not mutating the param, e.g.
```suggestion
				const userAgentDetails = { category: Category.DataStore, ...customUserAgent };
```

2023-03-11 01:49 UTC, cshfang commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +import { Category, Framework } from '@aws-amplify/core/src';
Here and everywhere else - I don't think you need the `/src`
```suggestion
import { Category, Framework } from '@aws-amplify/core';
```

2023-03-11 01:49 UTC, cshfang commented on packages/api-graphql/src/GraphQLAPI.ts
> +		}
Do we mean to update the reference from the parameter directly? Generally speaking, this is not desirable so I want to check if it is intentional

If not intentional I'd suggest just spreading the param so we're not mutating the param, e.g.
```suggestion
		const userAgentDetails = { category: Category.API, ...customUserAgent };
```

2023-03-11 01:49 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	}
Ditto here about mutating the param. We should be able to use the same pattern as well of spreading the param - since `detectFramework` isn't exactly a compute heavy function.
```suggestion
	const userAgentDetails = { framework: detectFramework(), ...userAgentDetails }
```

2023-03-11 01:49 UTC, cshfang commented on packages/core/src/constants.ts
> +	JS = '4:0',
Imo, this ought to be ~~JS~~ None

2023-03-11 01:49 UTC, cshfang commented on packages/core/src/constants.ts
> +export const enum Framework {
React native?

2023-03-13 16:55 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +		)
Good question: for this first PR I included frameworks that I haven't tested yet, going to pair it down for the initial state and add them in as I am able to test in each framework. I'll make a note for myself when I get to angular to verify that we don't capture angular 2 for earlier versions of angular.

2023-03-13 17:09 UTC, erinleigh90 commented on packages/datastore/src/sync/processors/mutation.ts
> +				}
Thanks Chris, this is the super neat solution I was hoping for!

2023-03-13 18:52 UTC, cshfang requested changes

2023-03-16 18:01 UTC, erinleigh90 commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +import { Category, Framework } from '@aws-amplify/core';
Yes, these were not from me but we should definitely make note of it.

2023-03-16 18:01 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +	return Framework.None;
Yes, for now. I will add the frameworks back in one by one when I get to that phase and as they are each validated in a sample app.

2023-03-16 18:01 UTC, erinleigh90 commented on packages/datastore/src/sync/processors/mutation.ts
> +					userAgentDetails,
Thank you! Good catch.

2023-03-16 20:15 UTC, cshfang approved these changes

2023-03-16 20:15 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	return [packageDetails, `(${Object.values(userAgentDetails).sort().toString()})`].filter(Boolean).join(' ');
Nit: I don't think we need the `toString()` since it's already being interpolated.

Also, I think what you have here works fine but it's also hard for readers to easily digest
* Create an array of two string
* Filter by coercing to boolean
* Join it with a space to form final string
All happening on a single line

I think you can simplify the intent
* If there are packageDetails, add it to the front of the string
```ts
	return `${packageDetails && `${packageDetails} `}(${Object.values(userAgentDetails).sort()})`;
```

2023-03-20 18:22 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +	return [packageDetails, `(${Object.values(userAgentDetails).sort().toString()})`].filter(Boolean).join(' ');
This absolutely makes sense and is much clearer.

2023-03-22 19:01 UTC, haverchuck reviewed
One high level question - The only places we are exposing user-agent configuration on public facing APIs is on those APIs which _already_ accepted such parameters (i.e. the user agent suffix)?

2023-03-22 23:37 UTC, closed without merging